version: "3"
networks:
  micro-net:
    driver: bridge
volumes:
  authentication-nodemodules:
  my-db:
services:
  db-service:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER}"]
      interval: 10s
      retries: 5
    networks:
      - micro-net
    restart: always
  
    environment:
      POSTGRES_USER: ${USER}  
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}                      
      
    ports:
      - '5432:5432'   
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data


  authentication-service:
    entrypoint: ["./entrypoint.sh"]
    build: ./authentication-service
    networks:
      - micro-net
    ports:
      - "3001:3001"
    depends_on:
       db-service:
         condition: service_healthy
    volumes:
      - ./authentication-service:/opt/myapp/Authentication-system1/authentication-service
      - authentication-nodemodules:/opt/myapp/Authentication-system1/authentication-service/node_modules
  